### ISSUE TITLE
openwrt web/system/software can't update lists

### ISSUE THREAD

**Issue by kylongmu** [OpenNuvoton/NUC980-OpenWrt#2]
Hi, 
I try to update lists, but failed with this message:
`Collected errors:
 * opkg_download: Failed to download https://downloads.openwrt.org/releases/22.03.0/targets/nuc980/iot/packages/Packages.gz, wget returned 8.`
 
I checked that downloads.openwrt.org without the tartet for nuc980
Is it not be supported?

**Comment by ychuang3** [comment]
Hi,

We have ported OpenWrt 22.03 NUC980, but did not submit to offical  release.
User can download the NUC980 OpenWrt 22.03 from GitHub:  https://github.com/OpenNuvoton/Nuvoton-OpenWrt-22.03
